name : sample build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: unbuntu-latest
    steps:
    - name: push code
      uses: actions/checkout@v3
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username:  ${{ secrets.DOCKER_USERNAME }}
        password:  ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sivasudhan/my_1st_image:latest
        build-args: |
          TAVILY_API_KEY=${{secrets.TAVILY_API_KEY}}
          GROQ_API_KEY=${{secrets.GROQ_API_KEY}}
        progress: plain


  